### ISSUE TITLE
[BUG] - Setting value to form (control) for ngx-mat-timepicker-field does not change displayed time

### ISSUE THREAD

**Issue by devAnky** [tonysamperi/ngx-mat-timepicker#111]
**Describe the bug**
When using ngx-mat-timepicker-field as a Form Control (via formControlName) and then trying to set it's value via controlName.setValue(...) or form.patchValue() on it's parent form the new value is not being displayed in the UI fields (The previous time is still being displayed, so no visible changes at all). BUT if you check the value of the Form Control or the form, you'll receive the new value. Side note: Setting initial values like in the stackblitz example does work... EDIT: It works when using ngModel and changing the value of the model...

**To Reproduce**
https://stackblitz.com/~/github.com/devAnky/ngx-mat-timepicker-field-set-value-bug

1. Click button 'Set time' to set the time
2. Observe that ther ui does not change at all
3. Click the button 'Submit form' to receive the current form control value

**Expected behavior**
When setting the value of the form control either directly or via the FormGroup  the ui fields should change their visible value accordingly.

**Desktop (if execution):**
 - Windows 11
 - Chrome

**Versions**
 - ngx-mat-timepicker version [17.1.0]
 - @angular/core version [17.2.0]
 - @angular/material version [17.2.2]
 - typescript version [5.3.2]

**Comment by tonysamperi** [comment]
Hello,

1. Nowhere in the docs is written that you can use form controls this way
2. You should use the search, because I discussed a similar case in the past and provided a clever workaround
3. It couldn't ever work cause of how it was implemented originally
4. Nope. NgModel doesn't work as well, cause of how it was implemented (very badly, the guy knows nothing about the matter)

That said, I could even implement the stuff, but it's a quite long implementation and as far as I agree that this behaviour should be natively supported, I don't think I'll be able to do this very soon.

Sorry.
