### ISSUE TITLE
[BUG] - (v16) After Keyboard Input I get TypeError: time.match is not a function

### ISSUE THREAD

**Issue by maukito** [tonysamperi/ngx-mat-timepicker#70]
Cannot set time manually

After a manual input with the keyboard of the time, I get the console error: TypeError: time.match is not a function.
You would get that if _time_ would not be a string.
The error points to your function:
```
    static parseTime(time, opts) {
        .........
        if (time.match(/\s/g)) {
```

**To Reproduce**
Enter the time with keyboard and press enter.

**Expected behavior**
Manual Time Input is possible.

**Desktop (if execution):**
 - Windows
 - Chrome

** Versions
 - ngx-mat-timepicker version 16.0.0
 - @angular/core version 16.0.3
 - @angular/material version 16.0.2
 - typescript version 4.9.5

**Comment by tonysamperi** [comment]
Hi
I definitely need more info.
Can you setup a blitz?
Also, you should use Typescript 5

**Comment by maukito** [comment]
ok will do the week after, next week I am on vacation...thx

**Comment by erikvorstenbosch** [comment]
I am running into the same issue.
I have created a [stackblitz](https://stackblitz.com/edit/stackblitz-starters-vcrjxz?file=src%2Fapp%2Fapp.component.html)

The input element is made editable by adding `[disableClick]="true"`. Then after entering a time with the keyboard and leaving the control the error message `ERROR Error: time.match is not a function` appears.

The full stacktrace with version 16.0.1 as seen in my own application (using Chrome on Windows) is:

```
22:01:18.086 app.component.html:5 ERROR TypeError: time.match is not a function
    at NgxMatTimepickerAdapter.parseTime (ngx-mat-timepicker.mjs:136:18)
    at NgxMatTimepickerAdapter.formatTime (ngx-mat-timepicker.mjs:72:33)
    at set value [as value] (ngx-mat-timepicker.mjs:2177:46)
    at NgxMatTimepickerDirective.updateValue (ngx-mat-timepicker.mjs:2236:19)
    at NgxMatTimepickerDirective_change_HostBindingHandler (ngx-mat-timepicker.mjs:2272:99)
    at executeListenerWithErrorHandling (core.mjs:15762:16)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:15795:22)
    at HTMLInputElement.<anonymous> (platform-browser.mjs:666:17)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:25948:55
```

The issue is appearing is ng-mat-timepicker version 16.0.1 as well as 15.1.7.

**Comment by tonysamperi** [comment]
Hi @erikvorstenbosch and thanks for taking the time to create the blitz.
Let me start by telling both of you that in the demo site there's the code to achieve what you need without triggering any errors:
![image](https://github.com/tonysamperi/ngx-mat-timepicker/assets/5957244/868da26c-72d1-4789-adaa-1ee47253bd3f)

By the way I did some checks and I can already changed the code.
From my tests, I don't see any other triggers of the `change Hostlistener` so I guess we're fine with the mod.

I'm going to publish on v16 (since it has less active installations than v15). If no one complains I will create a later release for v15 and v14.
