### ISSUE TITLE
[BUG] - ExpressionChangedAfterItHasBeenCheckedError when used in dialog

### ISSUE THREAD

**Issue by Marax** [tonysamperi/ngx-mat-timepicker#77]
**Describe the bug**
When using picker placed in other dialog, closing it is causing ExpressionChangedAfterItHasBeenCheckedError

I've saw there is already some hack to solve other ExpressionChanged issue in the code btw but I think this is different issue.

**To Reproduce**
- [stackblitz](https://stackblitz.com/edit/stackblitz-starters-bw2rbw?file=src%2Findex.html)
- Click the button to open dialog
- click the watch to open nxg-mat-timepicker (note styles broken at slackbitz but ignore that)
- close that picker dialog (cancel or OK)
- see console: Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'mat-focused': 'true'. Current value: 'false'.

** Versions
 - ngx-mat-timepicker "16.0.2"
 - @angular/core 16.1.4
 - @angular/material 16.1.4
 - typescript 4.0.2

**Comment by tonysamperi** [comment]
Ok I'll do some checks...although...you know that it's not really a bug don't you? When you compile prod you won't get the error. This is just in development mode because you get warned you MAY be doing something wrong.
But it's not the case, since it's a focus problem caused by Angular Material, not by this library.
I don't remember using any cdk-autofocus or anything similar...

Cheers

**Comment by tonysamperi** [comment]
@Marax found it! There actually was a `cdkTrapFocusAutoCapture`.
I guess I can remove that especially since this dialog is not exactly a11y compliant (it's not a big work, but still I should check the keyboard behaviours).
I'm releasing the new patched version in a few minutes!
