### ISSUE TITLE
Bug - Time picker not preserving selected time when using "appendToInput"

### ISSUE THREAD

**Issue by ot-esteinecke** [tonysamperi/ngx-mat-timepicker#93]
In my application, users are often importing data, so [defaultTime] works as an initial starting point. However there are occasions where they will want to update the time more than once in a session. If they select a new time [defaultTime] does not capture the time change. The documentation didn't seem to catch this scenario. From a very cursory overview of the code, I see a couple ways this could be addressed:

1. Create a new input that will take an observable or behavior subject that can update the time
2. Enable `open()` to take a partial config object.

If there is already a pretty simple way to accomplish this, enlighten me.

EDIT: While this is accomplishable through using `ngx-mat-timepicker-field`, forcing the timepicker itself to be a form-control removes the user's agency to have this capability with their own easily configurable input styling.

**Comment by tonysamperi** [comment]
The solution is not as simple as it seems, because of how this was originally implemented.
What I have in mind is recreating this library from scratch, solving its architectural issues and also working with formControls. 
I have no idea why the original author worked this way, honestly I have a completely different approach...

In the meantime, hoping I understood what you're trying to do, could you try something like: 

```html
...
[defaultTime]="selectedTime || defaultTime"
...
```

and let me know?

**Comment by tonysamperi** [comment]
@ot-esteinecke

![image](https://github.com/tonysamperi/ngx-mat-timepicker/assets/5957244/caeee6f3-074f-400c-b480-b245b60bc793)

**Comment by tonysamperi** [comment]
@ot-esteinecke 

1. You should describe better your problem
2. You should report all the required data (see the bug template)
3. I can't reproduce your problem in the demo website, the dialog opens with the selected time (I also recently fixed a bug that was preventing the time from showing correctly when you had min/max)
4. You should create a blitz reproducing your problem

This issue will be deleted in 48 hours

**Comment by ot-esteinecke** [comment]
1. It is a little bit complicated, so I can understand what appears to look like frustration. Please pardon me as I am far more used to fixing issues than reporting them. I have frustrations with bad or incomplete reports many times. It actually took me a bit of effort to reproduce since in most situations, `[defaultTime]` captures the change. I have a custom listener on the control that updates the variable used for `[defaultTime]`. Instead of linking `<input />` to the form control directly, I update it with a `[value]` input. The reason for this is the `formgroup` is untyped, defined through an `@Input`. I am sure that if I were to directly link the control directly to the `<input />` we would not be having this conversation.
2. I don't see this as a bug, but an enhancement, so that's why I did not follow that template. I apologize I do not have a clear definition of what you see as a bug. If you see it that way, I will make this a bug. Please let me know.
3. Answered with 4.
4. [Here you go](https://stackblitz.com/edit/ngx-mat-timepicker-wtkq95)

**Comment by tonysamperi** [comment]
1. You don't need to project, if you're frustated it's your problem. I'm not frustrated, I just gave you the rules to a good reporting
2. You made something convoluted but it could be handled way easier than that (sending the updated blitz in a bit)
3. I didn't say it's not an enhancement, I only said you should report all the info in the bug template, which would have helped me knowing from the beginning that the fix I was talking about was not made in v16.

Cheers

**Comment by tonysamperi** [comment]
**UPDATE**

Basically this bug was born when I switched to standalone components.
I'm 99% sure that until version 15 there shouldn't be any issue.

By the way.

[Here](https://stackblitz.com/edit/ngx-mat-timepicker-dvpugk) dear @ot-esteinecke you can see that less is more.
I didn't quite get all the stuff with observables...even if the formGroup is defined by an @Input at that point I would update the inner formGroup when the @Input changes.

I'm publishing the fix in a few minutes for both v17 and v16.

Cheers

**Comment by tonysamperi** [comment]
Released
